/**
 * The "help me" bundle: one Markdown file with everything a helper needs to
 * diagnose a stuck setup — project summary, health warnings, machine
 * readiness, recent runs, and the last error lines from the logs. Designed
 * to be pasted into a chat, an issue, or an email. Env values never appear.
 */

import type { DoctorWarning, ProcessLogEvent, ScanResult } from '../types.js';
import type { RunHistoryEntry } from '../history/index.js';
import type { SystemReport } from '../system/index.js';
import { buildFactSheet, buildPlainSummary } from '../summary/index.js';

export interface HelpBundleInput {
  scan: ScanResult;
  warnings: DoctorWarning[];
  system: SystemReport;
  history?: RunHistoryEntry[];
  /** Recent log events; only the tail (and error lines) are included. */
  logs?: ProcessLogEvent[];
  devsurfaceVersion: string;
}

const LOG_TAIL_LINES = 40;

/** Compose the shareable Markdown help bundle. */
export function renderHelpBundle(input: HelpBundleInput): string {
  const { scan, warnings, system, devsurfaceVersion } = input;
  const lines: string[] = [];

  lines.push(`# Help request: ${scan.projectName}`);
  lines.push('');
  lines.push(
    `_Generated by DevSurface v${devsurfaceVersion} on ${new Date().toISOString()}. ` +
      'No secret values are included — env keys are listed by name only._'
  );
  lines.push('');

  lines.push('## The project, in plain English');
  lines.push('');
  lines.push(buildPlainSummary(scan));
  lines.push('');
  lines.push('| Fact | Value |');
  lines.push('| ---- | ----- |');
  for (const fact of buildFactSheet(scan)) {
    lines.push(`| ${fact.label} | ${fact.value.replace(/\|/g, '\\|')} |`);
  }
  lines.push('');

  lines.push('## My computer');
  lines.push('');
  lines.push(
    `${system.osName} (${system.arch}), ${system.cpuCount} CPU cores, ${system.totalMemoryGb} GB RAM (${system.freeMemoryGb} GB free).`
  );
  for (const check of system.checks) {
    const glyph = check.ok === true ? '✅' : check.ok === false ? '❌' : '➖';
    lines.push(`- ${glyph} ${check.label}: ${check.detail}`);
  }
  lines.push('');

  lines.push('## Health warnings');
  lines.push('');
  if (warnings.length === 0) {
    lines.push('None — the doctor found nothing wrong.');
  } else {
    for (const warning of warnings) {
      lines.push(`- **[${warning.severity}] ${warning.title}** — ${warning.message}`);
    }
  }
  lines.push('');

  const history = (input.history ?? []).slice(0, 8);
  if (history.length > 0) {
    lines.push('## Recent script runs');
    lines.push('');
    for (const entry of history) {
      const outcome =
        entry.status === 'exited' && entry.exitCode === 0
          ? 'succeeded'
          : entry.status === 'stopped'
            ? 'was stopped'
            : `failed (exit ${entry.exitCode ?? '?'})`;
      lines.push(
        `- \`${entry.script}\` ${outcome} after ${Math.round(entry.durationMs / 1000)}s (${entry.endedAt})`
      );
    }
    lines.push('');
  }

  const logs = input.logs ?? [];
  if (logs.length > 0) {
    const errorLines = logs.filter((log) => log.stream === 'stderr').slice(-LOG_TAIL_LINES);
    const tail = (errorLines.length > 0 ? errorLines : logs.slice(-LOG_TAIL_LINES)).slice(
      -LOG_TAIL_LINES
    );
    lines.push(`## Last ${tail.length} log lines${errorLines.length > 0 ? ' (errors)' : ''}`);
    lines.push('');
    lines.push('```text');
    // Strip ANSI color codes so the bundle reads cleanly everywhere.
    const ansiPattern = new RegExp(`${String.fromCharCode(27)}\\[[0-9;]*m`, 'g');
    for (const log of tail) {
      lines.push(`[${log.script}] ${log.message.replace(ansiPattern, '').slice(0, 500)}`);
    }
    lines.push('```');
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push(
    '_Helper checklist: 1) check the health warnings above, 2) check the tool versions, ' +
      '3) read the last error lines — the first error is usually the real one._'
  );
  lines.push('');
  return lines.join('\n');
}
